# 2D ARRAYS


In [62]:
import numpy as np
import pandas as pd
from array import array

In [63]:
twoDArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
twoDArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### INSERT A ROW/ COLUMN IN 2D ARRAY

In [64]:
# INSERT ROW/ COLUMN USING COLUMN INSERT FUNCTION

newtwoDArray = np.insert(twoDArray,0,[[17,28,19,20]], axis=1) # 0 represent the row/ column in which you need to add row / column
# Axis = 0 --> represent rows, Axis = 1 --> represent columns
newtwoDArray


array([[17,  1,  2,  3,  4],
       [28,  5,  6,  7,  8],
       [19,  9, 10, 11, 12],
       [20, 13, 14, 15, 16]])

In [65]:
# INSERTING THE NEW ROW/COLUMNS WITHOUT INSERT FUNCTION

def insert_function(arr,elements,index,axis):

    twoDArray = np.concatenate((arr[:index],[elements],arr[index:]),axis)
    # To add a column, set axis=1 and ensure 'elements' is a column vector
    # Example usage: insert_function(twoDArray, [[30], [31], [32], [33]], 1, 1)
    return twoDArray

insert_function(twoDArray,[25,26,27,28],3,0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [25, 26, 27, 28],
       [13, 14, 15, 16]])

In [66]:
# USE APPEND FUNCTION TO ADD NEW ROW/ COLUMN AT THE END OF AN 2D ARRAY

np.append(twoDArray,[[31,32,33,43]],axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [31, 32, 33, 43]])

In [67]:
# To append a new column, the shape must match (4, 1) for twoDArray with shape (4, 4)
# new_column = np.array([[35], [36], [37], [38]])
np.append(twoDArray, [[35], [36], [37], [38]], axis=1)

array([[ 1,  2,  3,  4, 35],
       [ 5,  6,  7,  8, 36],
       [ 9, 10, 11, 12, 37],
       [13, 14, 15, 16, 38]])

In [68]:
# ACCESS 2D ARRAY ELEMENTS

def accessElement(array, row_index, col_index):
    if(row_index >= len(array)|(col_index >= len(array))):
        return 'incorrect index'
    else:
        return array[row_index][col_index]

accessElement(twoDArray,5,5)
# accessElement(twoDArray, 3, 3)

'incorrect index'

In [69]:
# TRAVERSE 2D ARRAY

def twoDtraversal(array):
    for i in range(len(array)): # this will find the length of rows if we use len(array)
        print('\t')
        for j in range(len(array[0])): # this will find the length of column if we use len(array[0])
            print(array[i][j])
    

twoDtraversal(twoDArray)

	
1
2
3
4
	
5
6
7
8
	
9
10
11
12
	
13
14
15
16


In [70]:
# SEARCHING FOR AN ELEMENT IN 2D ARRAY

def search_element(array,element):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if(array[i][j] == element):
                return i, j
    return 'The element is not found!'
search_element(twoDArray, 11)

(2, 2)

In [71]:
twoDArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# DELETE A ROW IN 2D ARRAY WITHOUT USING DELETE FUNCTION

def delete_row(array,row_index,axis):
    # Concatenate all rows except the one at index 'row_index'
    return np.concatenate((array[:row_index],array[row_index+1:]),axis)

delete_row(twoDArray,2,0)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [ ]:
# DELETE A COLUMN IN 2D ARRAY WITHOUT USING DELETE FUNCTION

def delete_column(array, col_index):
    # Concatenate all columns except the one at index 'col_index'
    return np.concatenate((array[:, :col_index], array[:, col_index+1:]), axis=1)

# Example: delete the column at index 2
delete_column(twoDArray, 2)


array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12],
       [13, 14, 16]])

In [ ]:
# DELETE A ROW/COLUMN IN 2D ARRAY WITHOUT USING DELETE FUNCTION

def delete_elements(array,index,axis):
    
    if axis==0:
        return np.concatenate((array[:index],array[index+1:]),axis=0)
    elif axis==1:
        return np.concatenate((array[:,:index],array[:,index+1:]),axis=1)
delete_elements(twoDArray,2,1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12],
       [13, 14, 16]])

In [83]:
# DELETE ROW/COLUMN USING DELETE FUNCTION\

np.delete(twoDArray,0,axis=1)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])